Making success check message not overflow and fix hanging pendings (#37)
* Making success check message not overflow

Success message on PRs was so long that it was getting cut off and GH doesn't let you copy from the `hover for additional details (...)`

* Completed shortened name for cf

* added finally task to set status of commits

* Added state var for pipeline status for finally states

* Changed variable names to be valid for pr statuses

* changed location of set helm status to failed

* Fixed cf-status to cf_status

* Fixed sed in special skit task

* Change build-properties to be relative path

* Fixed deploy target substitution in skit-verify task

* Modified gh statuses and added status variables

* Modified pipeline errors

* Add exit 1 to force task to fail in cf

* Revert "Add exit 1 to force task to fail in cf"

This reverts commit ba0126c1b4e4c26b77a352de14fcf3b8e6cb38ff.

* Removed cf/helm_status from pl added to task, ensure pl_status is set in task

diff --git a/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml b/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml
--- a/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml
+++ b/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml
@@ -140,6 +140,10 @@ spec:
             cat $SHUTTLE_PROPERTIES_FILE
         fi
 
+        if ! grep -q "pl_status=" < $SHUTTLE_PROPERTIES_FILE
+          echo "pl_status=failed" >> $SHUTTLE_PROPERTIES_FILE
+        fi
+
         if [ "${DEPLOY_TARGET}" == "helm" ] || [ "${DEPLOY_TARGET}" == "both" ] && [ "${ENABLED_HELM}" == "false" ]; then
             echo "Helm pipeline is disabled for this toolchain"
             exit 0
@@ -177,6 +181,27 @@ spec:
         source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/verification_experience_test.sh")
 
         # Record task results
+        if [ "$SHUTTLE_PROPERTIES_FILE" ]; then
+          echo "${DEPLOY_TARGET}_status=success" >> $SHUTTLE_PROPERTIES_FILE
+
+          if [ "${ENABLED_HELM}" == "true" ] && [ "${ENABLED_CF}" == "true" ]; then
+            if grep -q "cf_status=success" < $SHUTTLE_PROPERTIES_FILE && grep -q "helm_status=success" < $SHUTTLE_PROPERTIES_FILE; then
+              sed -ir "s/^[#]*\s*pl_status=.*/pl_status=success/" $SHUTTLE_PROPERTIES_FILE
+            fi
+          elif [ "${ENABLED_HELM}" == "true" ] && [ "${ENABLED_CF}" == "false" ]; then
+            if grep -q "helm_status=success" < $SHUTTLE_PROPERTIES_FILE; then
+              sed -ir "s/^[#]*\s*pl_status=.*/pl_status=success/" $SHUTTLE_PROPERTIES_FILE
+            fi
+          elif [ "${ENABLED_HELM}" == "false" ] && [ "${ENABLED_CF}" == "true" ]; then
+            if grep -q "cf_status=success" < $SHUTTLE_PROPERTIES_FILE; then
+              sed -ir "s/^[#]*\s*pl_status=.*/pl_status=success/" $SHUTTLE_PROPERTIES_FILE
+            fi
+          else
+            sed -ir "s/^[#]*\s*pl_status=.*/pl_status=success/" $SHUTTLE_PROPERTIES_FILE
+          fi
+        fi
+        
+
         echo -n "$APP_URL" > $(results.app-url.path)
       volumeMounts:
         - mountPath: /cd-config
