Removed cf/helm_status from pl added to task, ensure pl_status is set in task

diff --git a/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml b/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml
--- a/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml
+++ b/tasks/skit-verify-alert-register/skit-verify-alert-register.yaml
@@ -140,6 +140,10 @@ spec:
             cat $SHUTTLE_PROPERTIES_FILE
         fi
 
+        if ! grep -q "pl_status=" < $SHUTTLE_PROPERTIES_FILE
+          echo "pl_status=failed" >> $SHUTTLE_PROPERTIES_FILE
+        fi
+
         if [ "${DEPLOY_TARGET}" == "helm" ] || [ "${DEPLOY_TARGET}" == "both" ] && [ "${ENABLED_HELM}" == "false" ]; then
             echo "Helm pipeline is disabled for this toolchain"
             exit 0
@@ -178,7 +182,7 @@ spec:
 
         # Record task results
         if [ "$SHUTTLE_PROPERTIES_FILE" ]; then
-          sed -ir "s/^[#]*\s*${DEPLOY_TARGET}_status=.*/${DEPLOY_TARGET}_status=success/" $SHUTTLE_PROPERTIES_FILE
+          echo "${DEPLOY_TARGET}_status=success" >> $SHUTTLE_PROPERTIES_FILE
 
           if [ "${ENABLED_HELM}" == "true" ] && [ "${ENABLED_CF}" == "true" ]; then
             if grep -q "cf_status=success" < $SHUTTLE_PROPERTIES_FILE && grep -q "helm_status=success" < $SHUTTLE_PROPERTIES_FILE; then
