feat: add retry logic

diff --git a/.bluemix/pipeline_cf.yml b/.bluemix/pipeline_cf.yml
--- a/.bluemix/pipeline_cf.yml
+++ b/.bluemix/pipeline_cf.yml
@@ -20,29 +20,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Build Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Build attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/build_cf.sh) and 'source' it from your pipeline job
-      #    source ./scripts/build_cf.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/build_cf.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/build_cf.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Build attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/deploy_cf.sh) and 'source' it from your pipeline job
+        #    source ./scripts/deploy_cf.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/build_cf.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/build_cf.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Build succeeded"
+          exit 0
+        fi
+      done
+      
+      if [ "${PASSED}" == "false" ]; then
+        msg="Build Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
   properties:
   - name: GIT_URL
     type: text
@@ -118,29 +132,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Deploy Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Deploy attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/deploy_cf.sh) and 'source' it from your pipeline job
-      #    source ./scripts/deploy_cf.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_cf.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_cf.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Deploy attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/deploy_cf.sh) and 'source' it from your pipeline job
+        #    source ./scripts/deploy_cf.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_cf.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_cf.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Deploy succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Deploy Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       api_key: ${API_KEY}
       application: ${APP_NAME}-monitored-cf
diff --git a/.bluemix/pipeline_helm.yml b/.bluemix/pipeline_helm.yml
--- a/.bluemix/pipeline_helm.yml
+++ b/.bluemix/pipeline_helm.yml
@@ -158,29 +158,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Build Container Image Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Build Container Image attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/containerize_build_container_img.sh) and 'source' it from your pipeline job
-      #    source ./scripts/containerize_build_container_img.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/containerize_build_container_img.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/containerize_build_container_img.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Build Container Image attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/containerize_build_container_img.sh) and 'source' it from your pipeline job
+        #    source ./scripts/containerize_build_container_img.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/containerize_build_container_img.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/containerize_build_container_img.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Build Container Image succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Build Container Image Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       api_key: ${API_KEY}
       region_id: ${REGISTRY_REGION_ID}
@@ -241,29 +255,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Deploy Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Deploy attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/deploy_helm.sh) and 'source' it from your pipeline job
-      #    source ./scripts/deploy_helm.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_helm.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_helm.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Deploy attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/deploy_helm.sh) and 'source' it from your pipeline job
+        #    source ./scripts/deploy_helm.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_helm.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_helm.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Deploy succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Deploy Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       region_id: ${PROD_REGION_ID}
       resource_group: ${PROD_RESOURCE_GROUP}
@@ -282,29 +310,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Check Health Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Check Health attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/deploy_check_health.sh) and 'source' it from your pipeline job
-      #    source ./scripts/deploy_check_health.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_check_health.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_check_health.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Check Health attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/deploy_check_health.sh) and 'source' it from your pipeline job
+        #    source ./scripts/deploy_check_health.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_check_health.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_check_health.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Check Health succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Check Health Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       region_id: ${PROD_REGION_ID}
       resource_group: ${PROD_RESOURCE_GROUP}
diff --git a/.bluemix/pipeline_knative.yml b/.bluemix/pipeline_knative.yml
--- a/.bluemix/pipeline_knative.yml
+++ b/.bluemix/pipeline_knative.yml
@@ -22,29 +22,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Build Container Image Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Build Container Image attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/build_cr.sh) and 'source' it from your pipeline job
-      #    source ./scripts/build_cr.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/build_cr.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/build_cr.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Build Container Image attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/build_cr.sh) and 'source' it from your pipeline job
+        #    source ./scripts/build_cr.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/build_cr.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/build_cr.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Build Container Image succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Build Container Image Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       api_key: ${API_KEY}
       region_id: ${REGISTRY_REGION_ID}
@@ -195,29 +209,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Deploy Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Deploy attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/deploy_knative.sh) and 'source' it from your pipeline job
-      #    source ./scripts/deploy_knative.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_knative.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_knative.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Deploy attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/deploy_knative.sh) and 'source' it from your pipeline job
+        #    source ./scripts/deploy_knative.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/deploy_knative.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/deploy_knative.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Deploy succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Deploy Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       region_id: ${PROD_REGION_ID}
       resource_group: ${PROD_RESOURCE_GROUP}
@@ -237,29 +265,43 @@ stages:
           exit 0
       fi
 
+      PASSED=false
       function check_exit
       {
         rv=$?
         if [ $rv != 0 ]; then
-            msg="Check Health Failed :spinning-siren:"
-            echo "${msg}"
-            # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
-            #    source ./scripts/slack_message.sh
-            # alternatively, you can source it from online script:
-            #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
-            source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
-            exit 1
+          echo "Check Health attempt failed"
+          PASSED=false
         else
-            exit 0
+          PASSED=true
         fi
       }
 
-      trap 'check_exit' EXIT
-      # copy the script below into your app code repo (e.g. ./scripts/test_health_knative.sh) and 'source' it from your pipeline job
-      #    source ./scripts/test_health_knative.sh
-      # alternatively, you can source it from online script:
-      #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/test_health_knative.sh")
-      source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/test_health_knative.sh")
+      for i in {1..3}
+      do
+        echo "Beginning Check Health attempt $i"
+        trap 'check_exit' EXIT
+        # copy the script below into your app code repo (e.g. ./scripts/test_health_knative.sh) and 'source' it from your pipeline job
+        #    source ./scripts/test_health_knative.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/test_health_knative.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/test_health_knative.sh")
+        if [ "${PASSED}" == "true" ]; then
+          echo "Check Health succeeded"
+          exit 0
+        fi
+      done
+
+      if [ "${PASSED}" == "false" ]; then
+        msg="Check Health Failed :spinning-siren:"
+        echo "${msg}"
+        # copy the script below into your app code repo (e.g. ./scripts/slack_message.sh) and 'source' it from your pipeline job
+        #    source ./scripts/slack_message.sh
+        # alternatively, you can source it from online script:
+        #    source <(curl -sSL "https://github.com/IBM/devex-skit-assets/raw/<release>/scripts/slack_message.sh")
+        source <(curl -sSL "$DEVX_SKIT_ASSETS_GIT_URL_RAW/scripts/slack_message.sh") "${msg}"
+        exit 1
+      fi
     target:
       region_id: ${PROD_REGION_ID}
       resource_group: ${PROD_RESOURCE_GROUP}
